CREATE TABLE SEAPORT
(
  ID               BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C55EC657_F7F8_4202_8D40_FDA74FA65DE3) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CITY             VARCHAR(255),
  COUNTRY_ISO_CODE VARCHAR(255),
  DESCRIPTION      VARCHAR(255),
  LATITUDE         DOUBLE,
  LONGITUDE        DOUBLE,
  NAME             VARCHAR(255)
)
