INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Sassnitz','balticsea','DE','Sassnitz',54.4966666,14.2125);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Ueckermunde',    'balticsea',    'DE',    'Ueckermunde',    54.7377777,    14.511111);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port Handlowy Swinoujscie',    'balticsea',    'PL',    'Swinoujscie',    53.905,    14.269722);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Police',    'balticsea',    'PL',    'Police',    53.5702777,    14.5752777);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Szczecin',    'balticsea',    'PL',    'Szczecin',    53.430555,    14.5872222);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Kołobrzeg',    'balticsea',    'PL',    'Kołobrzeg',    54.1861111,    15.5533333);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Darlowo',    'balticsea',    'PL',    'Darlowo',    54.4377777,    16.383055);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port Ustka',    'balticsea',    'PL',    'Port Ustka',    54.5944444,    16.8538888);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Wladyslawowo',    'balticsea',    'PL',    'Władysławowo',    54.7961111,    18.4186111);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Hel',    'balticsea',    'PL',    'Hel',    54.6069444,    18.7927777);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Gdynia',    'balticsea',    'PL',    'Gdynia',    54.5333333,    18.5413888);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Gdansk',    'balticsea',    'PL',    'Gdansk',    54.393333,    18.6700000);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port Polnocny',    'balticsea',    'PL',    'Gdansk',    54.39444444,    18.7208333);
INSERT INTO SEAPORT (NAME, DESCRIPTION, COUNTRY_ISO_CODE, CITY, LATITUDE, LONGITUDE)
VALUES ('Port of Elblag',    'balticsea',    'PL',    'Port of Elblag',    54.1736111,    19.388333);