POST localhost:8080/api/solve?cachedData=true
Authorization: Basic dXNlcjpwYXNz
Content-Type: application/json

{
	"origin" : {
		"latitude" : 48.802824,
		"longitude" : 13.236774
	},
	"destination" : {
		"latitude" : 50.952824,
		"longitude" : 14.886774
	},
	"plannedDepartureDateTime" : "2019-03-12T14:00"
}

###

GET localhost:8080/forecast?cachedData=true
Authorization: Basic dXNlcjpwYXNz
Content-Type: application/json

###

GET localhost:8080/forecast?cachedData=false
Authorization: Basic dXNlcjpwYXNz
Content-Type: application/json

###