POST localhost:8080/api/solve
Authorization: Basic dXNlcjo3N2U1MDExMS1jYTllLTRkODUtOGIxNy0zMzEyODcwYTFkYWE=
Content-Type: application/json

{
	"origin" : {
		"latitude" : 48.802824,
		"longitude" : 13.236774
	},
	"destination" : {
		"latitude" : 50.952824,
		"longitude" : 14.886774
	}
}

###